name: kiosk_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  cp949_codec: ^1.0.2
  esc_pos_utils_plus: ^2.0.4
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.6.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
